global:
  version: "testing"
  run_id: run_t02
  io:
    in_dir: /home/rhea/B/
    dest_dir: /home/rhea/W/artifacts
  log_dir: ./artifacts/log/

manifest:
  global:
    in_dir: ./mnt
  build:
    file_name: manifest.csv
  stats:
    file_name: metadata.csv
  validate:

mosaic:
  info: 
  footprint: 
  validate: 
  downsample:
    target_resolution: null
    target_width: null
    target_height: null
    overview_levels: null
    scale_factor: 0.278
    resampling: bilinear
    dtype: Byte
    compression: LZW
    tiled: true
    nodata: 0
    preserve_bounds: false

  tesselate:
    tile_size: 1024
    stride: 1024
    drop_partial: true
    shard_size: 2048
    shard_prefix: tiles
    manifest: csv


tile:
  quantize:
    dtype: float32
    scale: none
    p_low: 5.0
    p_high: 95.0
    per_band: true
    stats: sample
    num_samples: 1048
  read:
  label:
  write: 
  stats: 

label:
  init: 
  build:
  validate:

