global:
  version: "V5"
  run_id: r18
  io:
    in_dir: /home/rhea/C/
    dest_dir: /home/rhea/B/artifacts/
  log_dir: ./artifacts/log/

manifest:
  global:
    in_dir: ./mnt
  build:
    file_name: manifest.csv
    exempt: 
        - artifacts
        - run_test
  meta:
    file_name: metadata.csv
  validate:

metamosaic: 
  build: 
    manifest_name: metamosaics.csv
    summary_name: metamosaic_summary.csv

operations: 
  downsample:
    scale_factor: 0.50
    resampling: bilinear
    dtype: Byte
    compression: LZW
    tiled: true
    nodata: 0

    display:
      enabled: true
      method: percentile
      p_low: 2.0
      p_high: 98.0
      dst_min: 0
      dst_max: 255
      sample_windows: 512
      sample_size: 256

  tesselate: 
    shard_size: 2048
    shard_prefix: shard
    manifest_kind: csv 

plan: 
  tiles:
    tile_size: 240
    stride: 240
    drop_partial: true



segmentation:
  params:
    # for when masks miss small/skinny objects
    # higher = denser sampling, more time 
    points_per_side: 32
    
    # change for when too many bad masks
    # higher = keep only masks SAM thinks are better 
    # lower = more masks, more false positives
    pred_iou_thresh: 0.86
    
    # change when masks are too jagged 
    # higher = cleaner more stable masks 
    # lower = more permissive 
    stability_score_thresh: 0.92

    # change when small objects are missed 
    # 1 or 2 reruns prediction on image crops, often better for small objects. 
    crop_n_layers: 1

    # change when crops are too slow 
    crop_n_points_downscale_factor: 2 

    # change when spekles, holes, small junk masks
    # higher removes small disconeccted regions, holes
    min_mask_region_area: 64


    
heuristics: 
  soil:
  veg:
