global:
  version: "V5"
  run_id: 15
  io:
    in_dir: /home/rhea/B/
    dest_dir: /home/rhea/B/artifacts/
  log_dir: ./artifacts/log/

manifest:
  global:
    in_dir: ./mnt
  build:
    file_name: manifest.csv
    exempt: artifacts
  meta:
    file_name: metadata.csv
  validate:

metamosaic: 
  build: 
    manifest_name: metamosaics.csv

operations: 
  downsample:
    scale_factor: 0.50
    resampling: bilinear
    dtype: Byte
    compression: LZW
    tiled: true
    nodata: 0

    display:
      enabled: true
      method: percentile
      p_low: 2.0
      p_high: 98.0
      dst_min: 0
      dst_max: 255
      sample_windows: 512
      sample_size: 256

  tesselate: 
    shard_size: 2048
    shard_prefix: shard
    manifest_kind: csv 

plan: 
  tiles:
    tile_size: 240
    stride: 240
    drop_partial: true


tile:
  quantize:
    dtype: float32
    scale: none
    p_low: 5.0
    p_high: 95.0
    per_band: true
    stats: sample
    num_samples: 1048
